export default [
  { name: "Zara Vance", email: "zvance@devops.com", phone: "512-555-0654", dob: "1988-05-12", industry: "Technology", tier: "Silver", status: "accepted", isFirstTimeFounder: true },
  { name: "Quinn Sullivan", email: "qsullivan@finadvisors.com", phone: "415-555-0155", dob: "1975-11-20", industry: "Finance", tier: "Gold", status: "pending", isFirstTimeFounder: false },
  { name: "Dr. Simon Glass", email: "sglass@surgery.edu", phone: "617-555-0321", dob: "1982-03-04", industry: "Healthcare", tier: "Platinum", status: "accepted", isFirstTimeFounder: false },
  { name: "Miles Edgeworth", email: "miles@prosecution.gov", phone: "213-555-0678", dob: "1992-09-14", industry: "Legal", tier: "Gold", status: "pending", isFirstTimeFounder: true },
  { name: "Caleb Vance", email: "cvance@brokerage.com", phone: "702-555-0111", dob: "1985-07-22", industry: "Real Estate", tier: "Gold", status: "accepted", isFirstTimeFounder: true },
  { name: "Elena Fischer", email: "efischer@hedge.com", phone: "203-555-0442", dob: "1990-01-30", industry: "Finance", tier: "Gold", status: "pending", isFirstTimeFounder: false },
  { name: "Naomi Chen", email: "n.chen@techglobal.com", phone: "650-555-0189", dob: "1993-06-18", industry: "Technology", tier: "Platinum", status: "pending", isFirstTimeFounder: true },
  { name: "Janet Sterling", email: "jsterling@firm.org", phone: "312-555-0444", dob: "1978-12-05", industry: "Legal", tier: "Silver", status: "pending", isFirstTimeFounder: false },
  { name: "Julian Thorne", email: "j.thorne@luxuryhomes.com", phone: "305-555-0145", dob: "1984-04-11", industry: "Real Estate", tier: "Platinum", status: "pending", isFirstTimeFounder: false },
  { name: "Beatrice Holt", email: "bholt@wellness.com", phone: "503-555-0912", dob: "1991-08-28", industry: "Healthcare", tier: "Silver", status: "pending", isFirstTimeFounder: true },
  { name: "Sasha Ivanov", email: "sivanov@iplaw.com", phone: "202-555-0722", dob: "1987-10-10", industry: "Legal", tier: "Platinum", status: "accepted", isFirstTimeFounder: true },
  { name: "Marcus Sterling", email: "m.sterling@fintech.com", phone: "212-555-0198", dob: "1980-02-25", industry: "Finance", tier: "Platinum", status: "accepted", isFirstTimeFounder: false },
  { name: "Leo Hashimoto", email: "leo.h@cybersec.net", phone: "206-555-0432", dob: "1994-11-30", industry: "Technology", tier: "Platinum", status: "pending", isFirstTimeFounder: true },
  { name: "Desiree Dupont", email: "ddupont@parisrealty.com", phone: "212-555-0888", dob: "1983-05-19", industry: "Real Estate", tier: "Gold", status: "accepted", isFirstTimeFounder: false },
  { name: "Dr. Amara Okafor", email: "aokafor@neuro.org", phone: "312-555-0811", dob: "1986-07-07", industry: "Healthcare", tier: "Platinum", status: "accepted", isFirstTimeFounder: true },
  { name: "Andre Whitaker", email: "awhitaker@lawgroup.net", phone: "202-555-0167", dob: "1972-04-15", industry: "Legal", tier: "Gold", status: "accepted", isFirstTimeFounder: false },
  { name: "Kofi Arhin", email: "karhin@software.io", phone: "415-555-0922", dob: "1991-12-12", industry: "Technology", tier: "Gold", status: "accepted", isFirstTimeFounder: true },
  { name: "Aditi Sharma", email: "asharma@capital.io", phone: "212-555-0999", dob: "1989-03-21", industry: "Finance", tier: "Platinum", status: "accepted", isFirstTimeFounder: true },
  { name: "Vera Wang", email: "vera@estates.net", phone: "415-555-0333", dob: "1981-10-09", industry: "Real Estate", tier: "Platinum", status: "pending", isFirstTimeFounder: false },
  { name: "Gregori Markov", email: "gmark@biotech.ru", phone: "212-555-0555", dob: "1979-06-22", industry: "Healthcare", tier: "Gold", status: "pending", isFirstTimeFounder: false },
  { name: "Arthur Penhaligon", email: "arthur@heritage.com", phone: "617-555-0121", dob: "1968-08-30", industry: "Legal", tier: "Platinum", status: "accepted", isFirstTimeFounder: false },
  { name: "Reginald Banks", email: "rbanks@investment.net", phone: "704-555-0821", dob: "1974-01-14", industry: "Finance", tier: "Silver", status: "accepted", isFirstTimeFounder: false },
  { name: "Soren Nielsen", email: "soren@cloudscale.io", phone: "408-555-0777", dob: "1988-04-04", industry: "Technology", tier: "Gold", status: "accepted", isFirstTimeFounder: false },
  { name: "Dr. Elena Vance", email: "evance@healthway.org", phone: "310-555-0102", dob: "1985-06-16", industry: "Healthcare", tier: "Gold", status: "accepted", isFirstTimeFounder: true },
  { name: "Kent Brockman", email: "kent@developments.io", phone: "312-555-0222", dob: "1970-05-05", industry: "Real Estate", tier: "Silver", status: "accepted", isFirstTimeFounder: false }
];